/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.apresentacao;

import gui.Documento;
import gui.formasGeometricas.FormaGeometrica;
import gui.formasGeometricas.Ponto;
import gui.uteis.Iterador;
import gui.uteis.ListaEncadeada;

import javax.swing.*;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;



/**
 *
 * @author Tania
 */
public class PanelPrincipal extends javax.swing.JPanel implements InterfaceOuvintePanels{
    
//    private ListaEncadeada<Ponto> points;
    protected JLabel labelX, labelY;
    protected Documento doc;

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal(Documento doc) {
        this.doc = doc;
        initComponents();
//        points = new ListaEncadeada<>();
        
//        this.addMouseMotionListener(new MouseAdapter() {
//                    public void mouseDragged (MouseEvent event){
//                        //salva ponto na lista
//                        getPoints().inserirFim(event.getPoint());
//                        repaint();
//                    }
//
//                }
//        );
        
        
    }


    public void addListener4MousePos(JLabel labelX, JLabel labelY){
        this.labelX = labelX;
        this.labelY = labelY;
        this.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged (MouseEvent e){
                    //salva forma na lista
//                    getPoints().inserirFim( new Ponto( e.getPoint().x, e.getPoint().y ) );
//                    repaint();

                    //todo aqui vai ser diferenciado As formas geometricas,
                    // por enquanto so tem ponto
//                    doc.inserirFim( new Ponto( e.getPoint().x, e.getPoint().y ) );
                    novaFormaGeometrica( new Ponto( e.getPoint().x, e.getPoint().y ) );
                    atualizar(); // repinta JFrame


                    //atualiza as posicoes do mouse nos labels
                    labelX.setText( String.valueOf( e.getPoint().x ) );
                    labelY.setText( String.valueOf( e.getPoint().y ) );
                }


                @Override
                public void mouseMoved(MouseEvent e) {
                    //atualiza as posicoes do mouse nos labels
                    labelX.setText( String.valueOf( e.getPoint().x ) );
                    labelY.setText( String.valueOf( e.getPoint().y ) );
                }
            }
        );
    }
    
    @Override
    public void paintComponent (Graphics g){
        super.paintComponent(g);//limpa area de desenho        
         //desenha todos ospontos do array
//        for (int i=0; i<getPoints().getTamanho(); i++){
//            Ponto p = getPoints().pesquisar(i);
//            g.fillOval(p.getX(), p.getY(), 4, 4);
//        }

        //todo novo esquema de desenhar por iterador
        // e com FormaGeometrica
        Iterador<FormaGeometrica> it = doc.getIterador();
        FormaGeometrica forma;
        super.paintComponent(g);//limpa area de desenho

        while((forma = it.proximo()) != null) {
            forma.desenhar(g);
        }
    }

    @Override
    public void atualizar() {
        getParent().revalidate();
        repaint();
    }
    @Override
    public void novaFormaGeometrica(FormaGeometrica forma) {
        doc.inserirFim(forma);
    }
    
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

//    /**
//     * @return the points
//     */
//    public ListaEncadeada<Ponto> getPoints() {
//        return points;
//    }
//
//    /**
//     * @param points the points to set
//     */
//    public void setPoints(ListaEncadeada<Ponto> points) {
//        this.points = points;
//    }
//

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
